sudo: required

services:
  - docker

before_install:
  - docker build -t mahmoud990/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mahmoud990/docker-react npm run test

language: generic
